
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcvpdkqwjoerstxzhdgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjdnBka3F3am9lcnN0eHpoZGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4OTU1NDgsImV4cCI6MjA1OTQ3MTU0OH0.xD7ePrA0JYMJb8PmXpNvM1Z0MsY4lObjyAIvmXtRoq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
